docker image rm donkeywon/centos-openresty
docker image rm donkeywon/centos-php
docker image rm donkeywon/centos-redis
docker image rm donkeywon/centos-memcached
docker image rm donkeywon/centos-influxdb
docker image rm donkeywon/centos-kafka
docker image rm donkeywon/centos-kibana
docker image rm donkeywon/centos-es
docker image rm donkeywon/centos-base
docker image rm donkeywon/centos-build-base
docker image rm donkeywon/centos-zookeeper
docker image rm donkeywon/centos-mongodb
docker image rm donkeywon/centos-mysql
docker image rm donkeywon/centos-yapi
docker image rm donkeywon/centos-grafana
